// Wine server protocol types
//
// These mirror the C structures from include/wine/server_protocol.h,
// generated from server/protocol.def. Every struct crossing the FFI
// boundary is #[repr(C)] with compile-time size assertions.
//
// RequestCode enum and MSG_* constants are auto-generated by build.rs
// from protocol.def and server_protocol.h. Never edit those manually.

#![allow(non_camel_case_types)]

pub type obj_handle_t = u32;
pub type user_handle_t = u32;
pub type process_id_t = u32;
pub type thread_id_t = u32;
pub type data_size_t = u32;
pub type lparam_t = u64;
pub type object_id_t = u64;

// Request/reply headers -- every message starts with one of these.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct RequestHeader {
    pub req: i32,
    pub request_size: data_size_t,
    pub reply_size: data_size_t,
}

const _: () = assert!(std::mem::size_of::<RequestHeader>() == 12);

#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct ReplyHeader {
    pub error: u32,
    pub reply_size: data_size_t,
}

const _: () = assert!(std::mem::size_of::<ReplyHeader>() == 8);

// Auto-generated from protocol.def by build.rs:
//   - RequestCode enum + from_i32() + as_str()
//   - MSG_* constants
//   - All 306 request/reply structs with padding
//   - Default handler stubs on EventLoop for unimplemented opcodes
//   - dispatch_request() function routing all opcodes
mod generated {
    include!(concat!(env!("OUT_DIR"), "/protocol_generated.rs"));
}
pub use generated::*;

// Queue wake/changed bits (from winuser.h, not in protocol.def)
pub const _QS_KEY: u32 = 0x0001;
pub const _QS_MOUSEMOVE: u32 = 0x0002;
pub const _QS_MOUSEBUTTON: u32 = 0x0004;
pub const QS_POSTMESSAGE: u32 = 0x0008;
pub const _QS_TIMER: u32 = 0x0010;
pub const _QS_PAINT: u32 = 0x0020;
pub const QS_SENDMESSAGE: u32 = 0x0040;
pub const _QS_HOTKEY: u32 = 0x0080;
pub const QS_ALLPOSTMESSAGE: u32 = 0x0100;

